@ManufacturingApp_HostAddress = http://localhost:5169

###
# Get all products
GET {{ManufacturingApp_HostAddress}}/api/Products
Accept: application/json

###
# Get a specific product by ID
GET {{ManufacturingApp_HostAddress}}/api/Products/1
Accept: application/json

###
# Create a new product
POST {{ManufacturingApp_HostAddress}}/api/Products/
Content-Type: application/json
Accept: application/json

{
    "name": "New Product",
    "description": "Description of the new product",
    "sellingPrice": 25.50
}

###
# Update an existing product by ID
PUT {{ManufacturingApp_HostAddress}}/api/Products/1
Content-Type: application/json
Accept: application/json

{
    "name": "Updated Product",
    "description": "Updated description",
    "sellingPrice": 30.00
}

###
# Delete a product by ID
DELETE {{ManufacturingApp_HostAddress}}/api/Products/1
Accept: application/json

###
# Get all raw materials
GET {{ManufacturingApp_HostAddress}}/api/RawMaterials/
Accept: application/json

###
# Get a specific raw material by ID
GET {{ManufacturingApp_HostAddress}}/api/RawMaterials/1
Accept: application/json

###
# Create a new raw material
POST {{ManufacturingApp_HostAddress}}/api/RawMaterials/
Content-Type: application/json
Accept: application/json

{
    "name": "New Raw Material",
    "description": "Description of the new raw material"
}

###
# Update an existing raw material by ID
PUT {{ManufacturingApp_HostAddress}}/api/RawMaterials/1
Content-Type: application/json
Accept: application/json

{
    "name": "Updated Raw Material",
    "description": "Updated description"
}

###
# Delete a raw material by ID
DELETE {{ManufacturingApp_HostAddress}}/api/RawMaterials/1
Accept: application/json

###
# Get all recipes
GET {{ManufacturingApp_HostAddress}}/api/Recipes/
Accept: application/json

###
# Get a specific recipe by ID
GET {{ManufacturingApp_HostAddress}}/api/Recipes/1
Accept: application/json

###
# Create a new recipe
POST {{ManufacturingApp_HostAddress}}/api/Recipes/
Content-Type: application/json
Accept: application/json

{
    "id": 0,
    "name": "New Recipe",
    "description": "Description of the new recipe",
    "recipeRawMaterials": [
        {
            "rawMaterialId": 2,
            "rawMaterialName": "string",
            "quantity": 2.5
        }
    ],
    "recipeProducts": [
        {
            "productId": 2,
            "productName": "string",
            "quantity": 5.0
        }
    ]
}

###
# Update an existing recipe by ID
PUT {{ManufacturingApp_HostAddress}}/api/Recipes/4
Content-Type: application/json
Accept: application/json

{
    "id": 4,
    "name": "Updated Recipe",
    "description": "Updated description",
    "recipeRawMaterials": [
        {
            "rawMaterialId": 2,
            "rawMaterialName": "string",
            "quantity": 2.0
        }
    ],
    "recipeProducts": [
        {
            "productId": 2,
            "productName": "string",
            "quantity": 5.0
        }
    ], 
    "recipeSuppliers": []
}

###
# Delete a recipe by ID
DELETE {{ManufacturingApp_HostAddress}}/api/Recipes/1
Accept: application/json

###
# Get all suppliers
GET {{ManufacturingApp_HostAddress}}/api/Suppliers/
Accept: application/json

###
# Get a specific supplier by ID
GET {{ManufacturingApp_HostAddress}}/api/Suppliers/2
Accept: application/json

###
# Create a new supplier
POST {{ManufacturingApp_HostAddress}}/api/Suppliers/
Content-Type: application/json
Accept: application/json

{
    "id": 0,
    "name": "New Supplier",
    "description": "Description of the new supplier",
    "supplierRawMaterials": [
        {
            "rawMaterialId": 2,
            "rawMaterialName": "string",
            "price": 14.00
        }
    ]
}

###
# Update an existing supplier by ID
PUT {{ManufacturingApp_HostAddress}}/api/Suppliers/15
Content-Type: application/json
Accept: application/json

{
    "id": 15,
    "name": "Updated Supplier",
    "description": "Updated description",
    "supplierRawMaterials": [
        {
            "rawMaterialId": 6,
            "rawMaterialName": "test",
            "price": 18.00
        }
    ]
}

###
# Delete a supplier by ID
DELETE {{ManufacturingApp_HostAddress}}/api/Suppliers/4
Accept: application/json
